baseURL: 'https://your-site-here.com/'
canonifyURLs: true
canonifyurls: true
enableRobotsTXT: true
googleAnalytics: SERIOUSLY-DONT-DO-THIS
languageCode: en-us
enableInlineShortcodes: true
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    codeFences: false
    hl_Lines: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: tango
    tabWidth: 2
menu:
  footer:
    - identifier: icon-github
      name: name the link
      url: 'https://github.com/blah-blah-blah'

  me_elsewhere:
    - identifier: github
      name: github.com/blah-blah-blah
      url: 'https://github.com/blah-blah-blah'
  topnav:
    - identifier: a
      name: About
      title: About Your Site
      url: /about/
    - identifier: f
      name: RSS Feed
      title: 'RSS Feed for all of Your Site'
      url: /index.xml
    - identifier: m
      name: Site Map
      title: 'An index of various pages on Site'
      url: /site-map/

outputs:
  home:
    - HTML
    - JSON
    - RSS
    - ATOM
  page:
    - HTML
  section:
    - HTML
  taxonomies:
    - HTML
    - XML
mediaTypes:
  application/atom:
    suffixes:
    - "atom"
outputFormats:
  Atom:
    mediaType: application/atom
    baseName: index
    isPlainText: false
params:
  FediverseCreator: somebody@somewhere
  inline_css: true
  # Note: This parameter dictates if you want to render the rel="next"
  # and rel="prev" for all tag instances.  When withTagRels == true,
  # it almost triples the build time.
  withTagRels: true
  searchMySiteVerification: blergh-herghy
  CopyrightRelation:
    - name: Your University
      relationship: alumniOf
      type: EducationalOrganization
      url: 'https://somegreatplace.edu'
  organizationImagePath: 'path/to-image.jpg'
  authorName: My Glorious Chosen Name
  copyrightHolder: My Glorious Chosen Name
  copyrightHolderEmail: your-email@place-of-awesome.com
  replyToEmail: your-email@place-of-awesome.com
  copyrightHolderURL: 'https://yourgreatsite.com/about/'
  description: >-
    Something wonderful I'm sure
  docsUrlForRssV2: 'https://cyber.harvard.edu/rss/rss.html'
  firstPostDate: 2011-02-02
  googleSiteVerification: SERIOUSLY_DONT_USE_THIS_CRAP
  headline: Your Site's Headline
  image: /images/some-image.png
  iso8601_format: '2006-01-02'
  morePermissionsPermalink: 'https://your-site-name.com/more_permissions/'
  pagination_size: 10
  paginatedSections:
    - post
    - review
  PathToBlogrollOPML: '/blogroll.xml'
  sameAs:
    - 'https://github.com/some-github-name'
  siteHost: your-site-name.com
  title: Your Site Name
  withJsonLd: true
  foundingDate: "2021-02-02"
permalinks:
  posts: '/:year/:month/:day/:slug/'
  pages: '/:slug/'
related:
  includeNewer: true
  indices:
    - name: tags
      weight: 100
    - name: keywords
      weight: 100
    - name: date
      pattern: '2006'
      weight: 10
    - name: title
      weight: 100
  threshold: 20
  toLower: false
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
taxonomies:
  license: licenses
  series: series
  tag: tags
  syndication: syndications
theme: hugo-tufte
title: Your Site Here
